# Basic
title: é˜¿å¤š
subtitle: æ— çŸ¥æ— ç•
description: æœªæ¥çš„ä¸å¯çŸ¥, æ˜¯æˆ‘ä»¬å‰è¿›çš„åŸåŠ¨åŠ›
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: Aduo
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: PHP
url: "https://aduo.github.io/"

# Comment
comment:
    # disqus: leopard
    # duoshuo: Aduo 

# Social
social:
    weibo: 1370490960 
    github: aduo
    # twitter: 
    mail: aduo@outlook.com

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: 5542c23169d3b2b7659bd81416b8d1bf  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
# ga:
#    id: UA-84134159-3   
#    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:day/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: å…³äºæˆ‘, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"